# Python Built-in Function 형변환

print(abs(-1))
print(all([1, 2, 3, 4, 5, 6, 0]))
print(any([0, 0, 0, 1]))
print('1 ===========')
print(bool(''))
print(bool(' '))
print('2 ===========')
print(bool(1))
print(bool(0))
print('3 ===========')
print(chr(65))
print(chr(97))
print('4 ===========')
print(ord('A'))
print(ord('a'))
print('5 ===========')
print(dict([('one', 1), ('two', 2)]))
print('6 ===========')
print(float(10))
print(int(10.7))
print('7 ===========')
print(set('aaabbbccc'))
print(len(set('aaabbbccc'))) # 알파벳의 갯수